---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smpnsuto/public_html/ujian
    - /bin/mkdir -p $DEPLOYPATH
    - rsync -av --exclude='.git/' --exclude='.env' ./ $DEPLOYPATH
    - cd $DEPLOYPATH && chmod -R 775 ./
