---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smpnsuto/public_html/portal/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --exclude='.git/' --exclude='.next/' --exclude='node_modules/' --exclude='.env*' ./ $DEPLOYPATH
    - cd $DEPLOYPATH && npm install
    - cd $DEPLOYPATH && npm run build
    - touch $DEPLOYPATH/tmp/restart.txt
